apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-hello
  template:
    metadata:
      labels:
        app: flask-hello
    spec:
      containers:
      - name: flask
        image: hashicorp/http-echo:1.0.0
        args:
          - "-text=Hello World from GKE behind Nginx Ingress!"
          - "-listen=:5000"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-hello-svc
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: flask-hello
  ports:
  - port: 80
    targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-hello-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    # Prevent Nginx from redirecting HTTP -> HTTPS
    # (we use HTTP throughout for this demo; production would use HTTPS)
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-hello-svc
            port:
              number: 80
